# Use postgres/example user/password credentials
version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: reddit

    ports:
      - "5432:5432"
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports: 
        - "16543:80"
    depends_on: 
        - postgres   

  mongodb_cache:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 123
    #   MONGO_INITDB_DATABASE: reddit

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data_container:/data/blog

    restart: unless-stopped

volumes:
  mongodb_data_container:
