# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: reddit


    ports:
      - "5432:5432"

    restart: unless-stopped
